Input
mansipadgelwar/Midori_UI pull request #7
Opened 2022-02-07 16:21 UTC by mansipadgelwar

Add Input component

Input
1. Textarea
2. with validation and errors style
<img width="485" alt="Screenshot 2022-02-07 at 9 47 47 PM" src="https://user-images.githubusercontent.com/74247233/152828196-99fd3ac6-32b8-43e0-85b1-0afe8b622551.png">

2022-02-07 17:31 UTC, shrey27 approved these changes
Your input fields look good.

2022-02-07 18:12 UTC, manish591 requested changes

2022-02-07 18:12 UTC, manish591 commented on components/input/input.css
> +.input-icon.icons-left .input{
You are using over specific selectors. Avoid this.

2022-02-08 12:01 UTC, SomeEarth86 approved these changes

2022-02-08 12:33 UTC, manish591 approved these changes
Looking good. You can merge now.

2022-02-08 15:24 UTC, merged